channels:
- conda-forge
dependencies:
- python=3.11.13
- pip<=24.1.2
- pip:
  - mlflow==3.1.1
  - jaraco-classes==3.4.0
  - jaraco-collections==5.1.0
  - numpy==2.0.2
  - pathlib==1.0.1
  - pyspark==3.5.1
  - scipy==1.15.3
name: mlflow-env
